// Package abigen generates the Go view of the kernel/user ABI from
// bpf/include/allseer_event.h.
//
// # Why this exists
//
// The header is the ABI contract between the eBPF programs and the Go decoder,
// and its own preamble states the consequence of getting it wrong: "A mismatch
// does not produce a clean error; it produces plausible garbage that flows
// straight into governance decisions." A hand-written Go mirror of a C struct
// is a duplicate, and duplicates drift. The drift is silent, and what it
// corrupts is the evidence every downstream conclusion rests on.
//
// So the header is the single source of truth and this package derives the Go
// side from it. Nothing about the layout is written down twice.
//
// # Why a deliberately narrow parser
//
// This is not a C parser. It understands exactly the constructs
// allseer_event.h uses — integer #defines, one enum, plain structs of
// fixed-width scalars and char arrays, and a single named union — and it
// **refuses everything else with an error naming the line**.
//
// That refusal is the design. A parser that skipped a construct it did not
// understand would emit a Go struct missing a field, which is precisely the
// drift the generator exists to prevent, arriving through the tool meant to
// stop it. Refusing loudly means a future header change either generates
// correctly or fails the build; it never half-works.
//
// # What it does not do
//
// It emits the ABI shape and nothing above it. Translating a decoded record
// into event.Event, and mapping allseer_event_type onto capability.Kind
// through the M1 catalog, is a separate concern with a separate milestone issue
// — so this package imports neither pkg/event nor pkg/capability, and the
// generated code has no dependency beyond encoding/binary.
package abigen

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"strings"
)

// Normalize converts CRLF to LF.
//
// Applied to the header before both parsing and hashing. This repository's
// .gitattributes deliberately pins only the golden decision streams to LF and
// leaves source to the developer's core.autocrlf, so allseer_event.h is CRLF on
// a Windows checkout and LF on a Linux one. Without this, the digest embedded
// in the generated file would differ between the two and the staleness check
// would fail on whichever platform did not generate it — reporting drift that
// is not drift, which is worse than no check at all.
func Normalize(b []byte) []byte {
	return []byte(strings.ReplaceAll(string(b), "\r\n", "\n"))
}

// canonicalSourcePath renders a header path the same way regardless of the
// directory the generator was invoked from.
//
// It has to. `go generate` runs in the package directory and reaches the header
// as ../../../bpf/include/allseer_event.h, while the Makefile target and the
// staleness test reach it from the repository root. The path is recorded in the
// generated file's comment, so without this the two invocations produce
// different bytes and each reports the other's output as stale — a check that
// fires on how it was called rather than on what changed is worse than none.
func canonicalSourcePath(p string) string {
	p = strings.ReplaceAll(p, "\\", "/")
	for {
		switch {
		case strings.HasPrefix(p, "../"):
			p = p[3:]
		case strings.HasPrefix(p, "./"):
			p = p[2:]
		default:
			return p
		}
	}
}

// Generate parses a C header and returns formatted Go source for pkg.
//
// The whole pipeline in one call, because that is what both the command and the
// staleness test need: the test regenerates in memory and compares against the
// committed file, which is only a meaningful comparison if it runs exactly the
// same code path the command does.
func Generate(header []byte, headerPath, pkg string) ([]byte, error) {
	header = Normalize(header)

	h, err := Parse(string(header))
	if err != nil {
		return nil, fmt.Errorf("parsing %s: %w", headerPath, err)
	}

	m, err := Layout(h)
	if err != nil {
		return nil, fmt.Errorf("laying out %s: %w", headerPath, err)
	}

	sum := sha256.Sum256(header)
	m.HeaderSHA256 = hex.EncodeToString(sum[:])

	src, err := Emit(m, canonicalSourcePath(headerPath), pkg)
	if err != nil {
		return nil, fmt.Errorf("emitting Go for %s: %w", headerPath, err)
	}

	// Formatted here rather than left to the caller, because the committed file
	// and the regenerated bytes have to be comparable and gofmt is not
	// idempotent-by-accident: two runs that differ only in whitespace would
	// make the staleness check fire on a change that is not one.
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("the generator produced Go that does not parse: %w", err)
	}
	return out, nil
}
