package abigen

import (
	"fmt"
	"strings"
)

// Emit renders the laid-out model as Go source.
//
// Everything here is derived. No name, size, or offset in the output is written
// down by a human, which is the property that makes the generated file
// trustworthy: a reviewer checks the generator once, then checks header diffs
// forever after.
func Emit(m *Model, headerPath, pkg string) ([]byte, error) {
	var b strings.Builder

	writeFileHeader(&b, m, headerPath, pkg)
	writeBounds(&b, m)
	if err := writeEnums(&b, m); err != nil {
		return nil, err
	}
	writeSizes(&b, m)
	writeOffsets(&b, m)
	if err := writeTypes(&b, m); err != nil {
		return nil, err
	}
	if err := writeDecoders(&b, m); err != nil {
		return nil, err
	}

	return []byte(b.String()), nil
}

func writeFileHeader(b *strings.Builder, m *Model, headerPath, pkg string) {
	fmt.Fprintf(b, "// Code generated by internal/telemetry/abigen. DO NOT EDIT.\n")
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// Source:            %s\n", headerPath)
	fmt.Fprintf(b, "// Source SHA-256:    %s\n", m.HeaderSHA256)
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// Regenerate with `go generate ./internal/telemetry/abi/`. TestGeneratedFileIsNotStale\n")
	fmt.Fprintf(b, "// fails when this file and the header disagree, so the two cannot drift apart\n")
	fmt.Fprintf(b, "// silently -- which is the failure this whole arrangement exists to prevent.\n")
	fmt.Fprintf(b, "\npackage %s\n\n", pkg)
	fmt.Fprintf(b, "import (\n\t\"encoding/binary\"\n\t\"errors\"\n\t\"fmt\"\n)\n\n")
}

// writeBounds emits the header's integer defines, split by what they are.
//
// Two blocks rather than one, because the two kinds of define carry different
// obligations and a single comment can only be true of one of them. A bound
// caps what a probe can report; a define no array uses is a value the two sides
// compare. Emitting the second under the first's comment would put a false
// statement about the ABI into the file whose whole claim is that nothing in it
// was written by hand.
func writeBounds(b *strings.Builder, m *Model) {
	var bounds, constants []Define
	for _, d := range m.Defines {
		if d.UsedAsBound {
			bounds = append(bounds, d)
			continue
		}
		constants = append(constants, d)
	}

	if len(bounds) > 0 {
		fmt.Fprintf(b, "// Bounds declared in the header. They are hard limits on what a probe can\n")
		fmt.Fprintf(b, "// report: eBPF stack space is 512 bytes and the verifier rejects unbounded\n")
		fmt.Fprintf(b, "// copies, so a longer path is truncated rather than reported in full.\n")
		writeDefineBlock(b, bounds)
	}

	if len(constants) > 0 {
		fmt.Fprintf(b, "// Constants declared in the header that no array bound uses.\n//\n")
		fmt.Fprintf(b, "// These are values the kernel and user sides compare rather than limits on\n")
		fmt.Fprintf(b, "// what fits, so they are emitted apart from the bounds: a reader who takes one\n")
		fmt.Fprintf(b, "// of them for a cap on what a probe can report has misread the contract.\n")
		writeDefineBlock(b, constants)
	}
}

func writeDefineBlock(b *strings.Builder, defines []Define) {
	fmt.Fprintf(b, "const (\n")
	for _, d := range defines {
		fmt.Fprintf(b, "\t%s = %d // %s\n", goConstName(d.Name), d.Value, d.Name)
	}
	fmt.Fprintf(b, ")\n\n")
}

func writeEnums(b *strings.Builder, m *Model) error {
	for _, e := range m.Enums {
		typeName := goTypeName(e.Name)
		prefix := memberPrefix(e.Members)

		fmt.Fprintf(b, "// %s is the C enum %s.\n//\n", typeName, e.Name)
		fmt.Fprintf(b, "// The values are a wire contract: append only, never renumber.\n")
		fmt.Fprintf(b, "type %s uint32\n\n", typeName)

		fmt.Fprintf(b, "const (\n")
		for _, mem := range e.Members {
			fmt.Fprintf(b, "\t%s %s = %d // %s\n", goEnumMember(mem.Name, prefix), typeName, mem.Value, mem.Name)
		}
		fmt.Fprintf(b, ")\n\n")

		// String is emitted rather than left to a stringer pass, so the
		// generated file has exactly one producer and one staleness check.
		fmt.Fprintf(b, "// String returns the C enumerator name, or a decimal form for a value this\n")
		fmt.Fprintf(b, "// build does not know. An unknown value is rendered rather than hidden: it\n")
		fmt.Fprintf(b, "// means the loaded object is newer than this binary, and that is exactly the\n")
		fmt.Fprintf(b, "// drift a reader needs to see.\n")
		fmt.Fprintf(b, "func (v %s) String() string {\n\tswitch v {\n", typeName)
		for _, mem := range e.Members {
			fmt.Fprintf(b, "\tcase %s:\n\t\treturn %q\n", goEnumMember(mem.Name, prefix), mem.Name)
		}
		fmt.Fprintf(b, "\t}\n\treturn fmt.Sprintf(\"%s(%%d)\", uint32(v))\n}\n\n", typeName)

		fmt.Fprintf(b, "// IsKnown reports whether v is an enumerator this build was generated from.\n")
		fmt.Fprintf(b, "func (v %s) IsKnown() bool {\n\tswitch v {\n\tcase ", typeName)
		for i, mem := range e.Members {
			if i > 0 {
				fmt.Fprintf(b, ", ")
			}
			fmt.Fprintf(b, "%s", goEnumMember(mem.Name, prefix))
		}
		fmt.Fprintf(b, ":\n\t\treturn true\n\t}\n\treturn false\n}\n\n")

		fmt.Fprintf(b, "// All%ss returns every enumerator in declaration order.\n", typeName)
		fmt.Fprintf(b, "func All%ss() []%s {\n\treturn []%s{\n", typeName, typeName, typeName)
		for _, mem := range e.Members {
			fmt.Fprintf(b, "\t\t%s,\n", goEnumMember(mem.Name, prefix))
		}
		fmt.Fprintf(b, "\t}\n}\n\n")
	}
	return nil
}

func writeSizes(b *strings.Builder, m *Model) {
	fmt.Fprintf(b, "// Sizes, in bytes, under LP64 with natural alignment -- the model both\n")
	fmt.Fprintf(b, "// supported targets use. RecordSize is what one ring buffer record occupies\n")
	fmt.Fprintf(b, "// and what the startup layout check compares against the loaded object.\n")
	fmt.Fprintf(b, "const (\n")
	for _, s := range m.Structs {
		fmt.Fprintf(b, "\tSizeof%s = %d", goTypeName(s.Name), s.Size)
		if s.InternalPad > 0 {
			fmt.Fprintf(b, " // includes %d bytes of implicit padding between fields", s.InternalPad)
		}
		fmt.Fprintf(b, "\n")
	}
	for _, s := range m.Structs {
		if s.Name != m.Root {
			continue
		}
		for _, f := range s.Fields {
			if f.IsUnion() {
				fmt.Fprintf(b, "\n\t// Sizeof%s is the union's fixed worst-case reservation.\n", goFieldName(f.Name))
				fmt.Fprintf(b, "\tSizeof%s = %d\n", goFieldName(f.Name), f.Size)
			}
		}
		fmt.Fprintf(b, "\n\t// RecordSize is sizeof(%s).\n", s.Name)
		fmt.Fprintf(b, "\tRecordSize = Sizeof%s\n", goTypeName(s.Name))
	}
	fmt.Fprintf(b, ")\n\n")
}

func writeOffsets(b *strings.Builder, m *Model) {
	fmt.Fprintf(b, "// Field offsets, in bytes from the start of the enclosing struct.\n//\n")
	fmt.Fprintf(b, "// Emitted because an offset is the unit a reviewer can check against the C\n")
	fmt.Fprintf(b, "// header by eye, and because the eventual kernel-side static assertions have\n")
	fmt.Fprintf(b, "// to compare against something.\n")
	fmt.Fprintf(b, "const (\n")
	for i, s := range m.Structs {
		if i > 0 {
			fmt.Fprintf(b, "\n")
		}
		for _, f := range s.Fields {
			fmt.Fprintf(b, "\tOffset%s%s = %d\n", goTypeName(s.Name), goFieldName(f.Name), f.Offset)
		}
	}
	fmt.Fprintf(b, ")\n\n")
}

func writeTypes(b *strings.Builder, m *Model) error {
	for _, s := range m.Structs {
		fmt.Fprintf(b, "// %s mirrors C `struct %s`.\n", goTypeName(s.Name), s.Name)
		fmt.Fprintf(b, "type %s struct {\n", goTypeName(s.Name))
		for _, f := range s.Fields {
			gt, err := goFieldType(f)
			if err != nil {
				return fmt.Errorf("struct %s: %w", s.Name, err)
			}
			fmt.Fprintf(b, "\t%s %s // offset %d, %d bytes\n", goFieldName(f.Name), gt, f.Offset, f.Size)
		}
		fmt.Fprintf(b, "}\n\n")
	}
	return nil
}

func writeDecoders(b *strings.Builder, m *Model) error {
	fmt.Fprintf(b, "// Errors reported for a record that is not the size this build expects.\n//\n")
	fmt.Fprintf(b, "// Separate sentinels because they mean different things about the system: a\n")
	fmt.Fprintf(b, "// short record is a truncated read or a reader bug, while a long one means the\n")
	fmt.Fprintf(b, "// loaded object writes a bigger record than this binary was generated for,\n")
	fmt.Fprintf(b, "// which is layout drift and is not recoverable by reading fewer bytes.\n")
	fmt.Fprintf(b, "var (\n")
	fmt.Fprintf(b, "\tErrShortRecord = errors.New(\"abi: record shorter than the expected layout\")\n")
	fmt.Fprintf(b, "\tErrLongRecord  = errors.New(\"abi: record longer than the expected layout\")\n")
	fmt.Fprintf(b, ")\n\n")

	root := goTypeName(m.Root)
	fmt.Fprintf(b, "// DecodeRecord parses one ring buffer record.\n//\n")
	fmt.Fprintf(b, "// The length must match RecordSize exactly. A mismatch in either direction is\n")
	fmt.Fprintf(b, "// refused rather than tolerated: this is the boundary where kernel and user\n")
	fmt.Fprintf(b, "// space must agree byte for byte, and accepting a record of the wrong size is\n")
	fmt.Fprintf(b, "// how plausible garbage reaches a governance decision.\n")
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// Byte order is the host's, via binary.NativeEndian, because the probe wrote\n")
	fmt.Fprintf(b, "// these bytes on this machine. There is no conversion to do and no endianness\n")
	fmt.Fprintf(b, "// to assume.\n")
	fmt.Fprintf(b, "func DecodeRecord(raw []byte) (%s, error) {\n", root)
	fmt.Fprintf(b, "\tswitch {\n")
	fmt.Fprintf(b, "\tcase len(raw) < RecordSize:\n")
	fmt.Fprintf(b, "\t\treturn %s{}, fmt.Errorf(\"%%w: got %%d bytes, want %%d\", ErrShortRecord, len(raw), RecordSize)\n", root)
	fmt.Fprintf(b, "\tcase len(raw) > RecordSize:\n")
	fmt.Fprintf(b, "\t\treturn %s{}, fmt.Errorf(\"%%w: got %%d bytes, want %%d\", ErrLongRecord, len(raw), RecordSize)\n", root)
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\treturn decode%s(raw), nil\n}\n\n", root)

	for _, s := range m.Structs {
		name := goTypeName(s.Name)
		fmt.Fprintf(b, "// decode%s reads a %s from b, which must be at least Sizeof%s bytes.\n", name, name, name)
		fmt.Fprintf(b, "func decode%s(b []byte) %s {\n\tvar v %s\n", name, name, name)
		for _, f := range s.Fields {
			if err := writeFieldDecode(b, f); err != nil {
				return fmt.Errorf("struct %s: %w", s.Name, err)
			}
		}
		fmt.Fprintf(b, "\treturn v\n}\n\n")
	}

	// Union accessors, on the root record only.
	for _, s := range m.Structs {
		if s.Name != m.Root {
			continue
		}
		for _, f := range s.Fields {
			if !f.IsUnion() {
				continue
			}
			for _, u := range f.Union {
				if u.StructRef == "" {
					return fmt.Errorf("union member %q is not a struct; only struct members are supported", u.Name)
				}
				mt := goTypeName(u.StructRef)
				fmt.Fprintf(b, "// %s interprets the payload union as %s.\n//\n", goFieldName(u.Name), mt)
				fmt.Fprintf(b, "// Which member is valid is decided by Type, and this accessor does not check\n")
				fmt.Fprintf(b, "// it. Deciding what a type value means is the decoder's job, not the ABI's.\n")
				fmt.Fprintf(b, "func (v %s) %s() %s {\n\treturn decode%s(v.%s[:])\n}\n\n",
					goTypeName(s.Name), goFieldName(u.Name), mt, mt, goFieldName(f.Name))
			}
		}
	}
	return nil
}

func writeFieldDecode(b *strings.Builder, f LaidField) error {
	name := goFieldName(f.Name)

	switch {
	case f.IsUnion():
		fmt.Fprintf(b, "\tcopy(v.%s[:], b[%d:%d])\n", name, f.Offset, f.Offset+f.Size)
		return nil

	case f.StructRef != "" && !f.IsArray():
		fmt.Fprintf(b, "\tv.%s = decode%s(b[%d:%d])\n", name, goTypeName(f.StructRef), f.Offset, f.Offset+f.Size)
		return nil

	case f.IsArray():
		if f.StructRef != "" {
			return fmt.Errorf("field %q is an array of structs, which this generator does not emit", f.Name)
		}
		if f.Elem == 1 {
			// Byte arrays copy wholesale, including the 2-D argv case, because
			// a [N][M]byte is contiguous and its element rows are addressable.
			if len(f.Dims) == 1 {
				fmt.Fprintf(b, "\tcopy(v.%s[:], b[%d:%d])\n", name, f.Offset, f.Offset+f.Size)
				return nil
			}
			row := f.Size / f.Dims[0]
			fmt.Fprintf(b, "\tfor i := 0; i < %d; i++ {\n", f.Dims[0])
			fmt.Fprintf(b, "\t\tcopy(v.%s[i][:], b[%d+i*%d:%d+(i+1)*%d])\n", name, f.Offset, row, f.Offset, row)
			fmt.Fprintf(b, "\t}\n")
			return nil
		}
		if len(f.Dims) != 1 {
			return fmt.Errorf("field %q is a multi-dimensional array of non-byte elements, which this generator does not emit", f.Name)
		}
		read, err := scalarRead(f.Type, fmt.Sprintf("b[%d+i*%d:]", f.Offset, f.Elem))
		if err != nil {
			return fmt.Errorf("field %q: %w", f.Name, err)
		}
		fmt.Fprintf(b, "\tfor i := 0; i < %d; i++ {\n\t\tv.%s[i] = %s\n\t}\n", f.Dims[0], name, read)
		return nil

	default:
		read, err := scalarRead(f.Type, fmt.Sprintf("b[%d:]", f.Offset))
		if err != nil {
			return fmt.Errorf("field %q: %w", f.Name, err)
		}
		fmt.Fprintf(b, "\tv.%s = %s\n", name, read)
		return nil
	}
}

// scalarRead renders the expression that reads one scalar out of a slice.
func scalarRead(cType, slice string) (string, error) {
	s, ok := scalars[cType]
	if !ok {
		return "", fmt.Errorf("type %q has no read form", cType)
	}
	switch s.size {
	case 1:
		if s.signed {
			return fmt.Sprintf("int8(%s[0])", slice), nil
		}
		return fmt.Sprintf("%s[0]", slice), nil
	case 2:
		if s.signed {
			return fmt.Sprintf("int16(binary.NativeEndian.Uint16(%s))", slice), nil
		}
		return fmt.Sprintf("binary.NativeEndian.Uint16(%s)", slice), nil
	case 4:
		if s.signed {
			return fmt.Sprintf("int32(binary.NativeEndian.Uint32(%s))", slice), nil
		}
		return fmt.Sprintf("binary.NativeEndian.Uint32(%s)", slice), nil
	case 8:
		if s.signed {
			return fmt.Sprintf("int64(binary.NativeEndian.Uint64(%s))", slice), nil
		}
		return fmt.Sprintf("binary.NativeEndian.Uint64(%s)", slice), nil
	}
	return "", fmt.Errorf("type %q has unsupported width %d", cType, s.size)
}

// goFieldType renders the Go type for a field.
func goFieldType(f LaidField) (string, error) {
	if f.IsUnion() {
		return fmt.Sprintf("[%d]byte", f.Size), nil
	}

	var base string
	switch {
	case f.StructRef != "":
		base = goTypeName(f.StructRef)
	default:
		s, ok := scalars[f.Type]
		if !ok {
			return "", fmt.Errorf("field %q has unsupported type %q", f.Name, f.Type)
		}
		base = s.goType
	}

	for i := len(f.Dims) - 1; i >= 0; i-- {
		base = fmt.Sprintf("[%d]%s", f.Dims[i], base)
	}
	return base, nil
}

// --- naming ------------------------------------------------------------------
//
// Every Go identifier is derived from the C one by rule, never by table. A
// table would be a second place the ABI is written down, which is the thing
// this package exists to avoid.

// initialisms are rendered upper-case so the generated names read as Go rather
// than as transliterated C.
var initialisms = map[string]string{
	"abi":  "ABI",
	"id":   "ID",
	"pid":  "PID",
	"tid":  "TID",
	"ppid": "PPID",
	"uid":  "UID",
	"gid":  "GID",
}

// goConstName turns ALLSEER_PATH_MAX into PathMax.
func goConstName(c string) string { return camel(strings.TrimPrefix(c, "ALLSEER_")) }

// goTypeName turns allseer_file_payload into FilePayload.
func goTypeName(c string) string { return camel(strings.TrimPrefix(c, "allseer_")) }

// goFieldName turns cgroup_id into CgroupID and _pad into Pad.
func goFieldName(c string) string { return camel(c) }

// goEnumMember strips the prefix shared by every member, then camel-cases what
// is left behind a short tag taken from that prefix: ALLSEER_EVT_FILE_OPEN with
// prefix ALLSEER_EVT_ becomes EvtFileOpen.
func goEnumMember(c, prefix string) string {
	rest := strings.TrimPrefix(c, prefix)
	tag := ""
	if prefix != "" {
		parts := strings.Split(strings.Trim(prefix, "_"), "_")
		tag = camel(parts[len(parts)-1])
	}
	return tag + camel(rest)
}

// memberPrefix returns the longest underscore-delimited prefix shared by every
// member name, including the trailing underscore.
func memberPrefix(members []EnumMember) string {
	if len(members) < 2 {
		return ""
	}
	parts := strings.Split(members[0].Name, "_")
	shared := len(parts) - 1 // never consume the whole name
	for _, m := range members[1:] {
		p := strings.Split(m.Name, "_")
		n := 0
		for n < shared && n < len(p)-1 && p[n] == parts[n] {
			n++
		}
		shared = n
	}
	if shared == 0 {
		return ""
	}
	return strings.Join(parts[:shared], "_") + "_"
}

// camel converts snake_case or SCREAMING_SNAKE to CamelCase, honoring
// initialisms and dropping the empty component a leading underscore produces.
func camel(s string) string {
	var b strings.Builder
	for _, part := range strings.Split(s, "_") {
		if part == "" {
			continue
		}
		lower := strings.ToLower(part)
		if init, ok := initialisms[lower]; ok {
			b.WriteString(init)
			continue
		}
		b.WriteString(strings.ToUpper(lower[:1]))
		b.WriteString(lower[1:])
	}
	return b.String()
}
