// Code generated by internal/telemetry/abigen. DO NOT EDIT.
//
// Source:            bpf/include/allseer_event.h
// Source SHA-256:    5d08a53b47948b349bf7528ddfbc7c8aff446db1a63964a033ac8d1589fb6bf2
//
// Regenerate with `go generate ./internal/telemetry/abi/`. TestGeneratedFileIsNotStale
// fails when this file and the header disagree, so the two cannot drift apart
// silently — which is the failure this whole arrangement exists to prevent.

package abi

import (
	"encoding/binary"
	"errors"
	"fmt"
)

// Bounds declared in the header. They are hard limits on what a probe can
// report: eBPF stack space is 512 bytes and the verifier rejects unbounded
// copies, so a longer path is truncated rather than reported in full.
const (
	PathMax = 256 // ALLSEER_PATH_MAX
	CommLen = 16  // ALLSEER_COMM_LEN
	ArgvMax = 8   // ALLSEER_ARGV_MAX
	ArgLen  = 64  // ALLSEER_ARG_LEN
)

// EventType is the C enum allseer_event_type.
//
// The values are a wire contract: append only, never renumber.
type EventType uint32

const (
	EvtUnknown    EventType = 0  // ALLSEER_EVT_UNKNOWN
	EvtFileOpen   EventType = 1  // ALLSEER_EVT_FILE_OPEN
	EvtFileWrite  EventType = 2  // ALLSEER_EVT_FILE_WRITE
	EvtFileUnlink EventType = 3  // ALLSEER_EVT_FILE_UNLINK
	EvtFileRename EventType = 4  // ALLSEER_EVT_FILE_RENAME
	EvtFileChmod  EventType = 5  // ALLSEER_EVT_FILE_CHMOD
	EvtProcExec   EventType = 6  // ALLSEER_EVT_PROC_EXEC
	EvtProcExit   EventType = 7  // ALLSEER_EVT_PROC_EXIT
	EvtNetConnect EventType = 8  // ALLSEER_EVT_NET_CONNECT
	EvtNetBind    EventType = 9  // ALLSEER_EVT_NET_BIND
	EvtNetSend    EventType = 10 // ALLSEER_EVT_NET_SEND
	EvtPrivChange EventType = 11 // ALLSEER_EVT_PRIV_CHANGE
	EvtPtrace     EventType = 12 // ALLSEER_EVT_PTRACE
)

// String returns the C enumerator name, or a decimal form for a value this
// build does not know. An unknown value is rendered rather than hidden: it
// means the loaded object is newer than this binary, and that is exactly the
// drift a reader needs to see.
func (v EventType) String() string {
	switch v {
	case EvtUnknown:
		return "ALLSEER_EVT_UNKNOWN"
	case EvtFileOpen:
		return "ALLSEER_EVT_FILE_OPEN"
	case EvtFileWrite:
		return "ALLSEER_EVT_FILE_WRITE"
	case EvtFileUnlink:
		return "ALLSEER_EVT_FILE_UNLINK"
	case EvtFileRename:
		return "ALLSEER_EVT_FILE_RENAME"
	case EvtFileChmod:
		return "ALLSEER_EVT_FILE_CHMOD"
	case EvtProcExec:
		return "ALLSEER_EVT_PROC_EXEC"
	case EvtProcExit:
		return "ALLSEER_EVT_PROC_EXIT"
	case EvtNetConnect:
		return "ALLSEER_EVT_NET_CONNECT"
	case EvtNetBind:
		return "ALLSEER_EVT_NET_BIND"
	case EvtNetSend:
		return "ALLSEER_EVT_NET_SEND"
	case EvtPrivChange:
		return "ALLSEER_EVT_PRIV_CHANGE"
	case EvtPtrace:
		return "ALLSEER_EVT_PTRACE"
	}
	return fmt.Sprintf("EventType(%d)", uint32(v))
}

// IsKnown reports whether v is an enumerator this build was generated from.
func (v EventType) IsKnown() bool {
	switch v {
	case EvtUnknown, EvtFileOpen, EvtFileWrite, EvtFileUnlink, EvtFileRename, EvtFileChmod, EvtProcExec, EvtProcExit, EvtNetConnect, EvtNetBind, EvtNetSend, EvtPrivChange, EvtPtrace:
		return true
	}
	return false
}

// AllEventTypes returns every enumerator in declaration order.
func AllEventTypes() []EventType {
	return []EventType{
		EvtUnknown,
		EvtFileOpen,
		EvtFileWrite,
		EvtFileUnlink,
		EvtFileRename,
		EvtFileChmod,
		EvtProcExec,
		EvtProcExit,
		EvtNetConnect,
		EvtNetBind,
		EvtNetSend,
		EvtPrivChange,
		EvtPtrace,
	}
}

// Sizes, in bytes, under LP64 with natural alignment — the model both
// supported targets use. RecordSize is what one ring buffer record occupies
// and what the startup layout check compares against the loaded object.
const (
	SizeofProc        = 56
	SizeofFilePayload = 544
	SizeofNetPayload  = 56
	SizeofExecPayload = 776
	SizeofPrivPayload = 32
	SizeofEvent       = 848

	// SizeofPayload is the union's fixed worst-case reservation.
	SizeofPayload = 776

	// RecordSize is sizeof(allseer_event).
	RecordSize = SizeofEvent
)

// Field offsets, in bytes from the start of the enclosing struct.
//
// Emitted because an offset is the unit a reviewer can check against the C
// header by eye, and because the eventual kernel-side static assertions have
// to compare against something.
const (
	OffsetProcCgroupID  = 0
	OffsetProcStartTime = 8
	OffsetProcPID       = 16
	OffsetProcTID       = 20
	OffsetProcPPID      = 24
	OffsetProcUID       = 28
	OffsetProcGID       = 32
	OffsetProcPad       = 36
	OffsetProcComm      = 40

	OffsetFilePayloadInode   = 0
	OffsetFilePayloadDevice  = 8
	OffsetFilePayloadBytes   = 16
	OffsetFilePayloadFlags   = 24
	OffsetFilePayloadMode    = 28
	OffsetFilePayloadPath    = 32
	OffsetFilePayloadNewPath = 288

	OffsetNetPayloadSaddr    = 0
	OffsetNetPayloadDaddr    = 16
	OffsetNetPayloadBytes    = 32
	OffsetNetPayloadSport    = 40
	OffsetNetPayloadDport    = 42
	OffsetNetPayloadFamily   = 44
	OffsetNetPayloadProtocol = 46
	OffsetNetPayloadSockType = 48
	OffsetNetPayloadPad      = 50

	OffsetExecPayloadArgc     = 0
	OffsetExecPayloadPad      = 4
	OffsetExecPayloadFilename = 8
	OffsetExecPayloadArgv     = 264

	OffsetPrivPayloadCapsEffective = 0
	OffsetPrivPayloadCapsPermitted = 8
	OffsetPrivPayloadOldUID        = 16
	OffsetPrivPayloadNewUID        = 20
	OffsetPrivPayloadOperation     = 24
	OffsetPrivPayloadPad           = 28

	OffsetEventTimestamp = 0
	OffsetEventType      = 8
	OffsetEventRet       = 12
	OffsetEventProc      = 16
	OffsetEventPayload   = 72
)

// Proc mirrors C `struct allseer_proc`.
type Proc struct {
	CgroupID  uint64   // offset 0, 8 bytes
	StartTime uint64   // offset 8, 8 bytes
	PID       uint32   // offset 16, 4 bytes
	TID       uint32   // offset 20, 4 bytes
	PPID      uint32   // offset 24, 4 bytes
	UID       uint32   // offset 28, 4 bytes
	GID       uint32   // offset 32, 4 bytes
	Pad       uint32   // offset 36, 4 bytes
	Comm      [16]byte // offset 40, 16 bytes
}

// FilePayload mirrors C `struct allseer_file_payload`.
type FilePayload struct {
	Inode   uint64    // offset 0, 8 bytes
	Device  uint64    // offset 8, 8 bytes
	Bytes   int64     // offset 16, 8 bytes
	Flags   uint32    // offset 24, 4 bytes
	Mode    uint32    // offset 28, 4 bytes
	Path    [256]byte // offset 32, 256 bytes
	NewPath [256]byte // offset 288, 256 bytes
}

// NetPayload mirrors C `struct allseer_net_payload`.
type NetPayload struct {
	Saddr    [16]uint8 // offset 0, 16 bytes
	Daddr    [16]uint8 // offset 16, 16 bytes
	Bytes    int64     // offset 32, 8 bytes
	Sport    uint16    // offset 40, 2 bytes
	Dport    uint16    // offset 42, 2 bytes
	Family   uint16    // offset 44, 2 bytes
	Protocol uint16    // offset 46, 2 bytes
	SockType uint16    // offset 48, 2 bytes
	Pad      uint16    // offset 50, 2 bytes
}

// ExecPayload mirrors C `struct allseer_exec_payload`.
type ExecPayload struct {
	Argc     uint32      // offset 0, 4 bytes
	Pad      uint32      // offset 4, 4 bytes
	Filename [256]byte   // offset 8, 256 bytes
	Argv     [8][64]byte // offset 264, 512 bytes
}

// PrivPayload mirrors C `struct allseer_priv_payload`.
type PrivPayload struct {
	CapsEffective uint64 // offset 0, 8 bytes
	CapsPermitted uint64 // offset 8, 8 bytes
	OldUID        uint32 // offset 16, 4 bytes
	NewUID        uint32 // offset 20, 4 bytes
	Operation     uint32 // offset 24, 4 bytes
	Pad           uint32 // offset 28, 4 bytes
}

// Event mirrors C `struct allseer_event`.
type Event struct {
	Timestamp uint64    // offset 0, 8 bytes
	Type      uint32    // offset 8, 4 bytes
	Ret       int32     // offset 12, 4 bytes
	Proc      Proc      // offset 16, 56 bytes
	Payload   [776]byte // offset 72, 776 bytes
}

// Errors reported for a record that is not the size this build expects.
//
// Separate sentinels because they mean different things about the system: a
// short record is a truncated read or a reader bug, while a long one means the
// loaded object writes a bigger record than this binary was generated for,
// which is layout drift and is not recoverable by reading fewer bytes.
var (
	ErrShortRecord = errors.New("abi: record shorter than the expected layout")
	ErrLongRecord  = errors.New("abi: record longer than the expected layout")
)

// DecodeRecord parses one ring buffer record.
//
// The length must match RecordSize exactly. A mismatch in either direction is
// refused rather than tolerated: this is the boundary where kernel and user
// space must agree byte for byte, and accepting a record of the wrong size is
// how plausible garbage reaches a governance decision.
//
// Byte order is the host's, via binary.NativeEndian, because the probe wrote
// these bytes on this machine. There is no conversion to do and no endianness
// to assume.
func DecodeRecord(raw []byte) (Event, error) {
	switch {
	case len(raw) < RecordSize:
		return Event{}, fmt.Errorf("%w: got %d bytes, want %d", ErrShortRecord, len(raw), RecordSize)
	case len(raw) > RecordSize:
		return Event{}, fmt.Errorf("%w: got %d bytes, want %d", ErrLongRecord, len(raw), RecordSize)
	}
	return decodeEvent(raw), nil
}

// decodeProc reads a Proc from b, which must be at least SizeofProc bytes.
func decodeProc(b []byte) Proc {
	var v Proc
	v.CgroupID = binary.NativeEndian.Uint64(b[0:])
	v.StartTime = binary.NativeEndian.Uint64(b[8:])
	v.PID = binary.NativeEndian.Uint32(b[16:])
	v.TID = binary.NativeEndian.Uint32(b[20:])
	v.PPID = binary.NativeEndian.Uint32(b[24:])
	v.UID = binary.NativeEndian.Uint32(b[28:])
	v.GID = binary.NativeEndian.Uint32(b[32:])
	v.Pad = binary.NativeEndian.Uint32(b[36:])
	copy(v.Comm[:], b[40:56])
	return v
}

// decodeFilePayload reads a FilePayload from b, which must be at least SizeofFilePayload bytes.
func decodeFilePayload(b []byte) FilePayload {
	var v FilePayload
	v.Inode = binary.NativeEndian.Uint64(b[0:])
	v.Device = binary.NativeEndian.Uint64(b[8:])
	v.Bytes = int64(binary.NativeEndian.Uint64(b[16:]))
	v.Flags = binary.NativeEndian.Uint32(b[24:])
	v.Mode = binary.NativeEndian.Uint32(b[28:])
	copy(v.Path[:], b[32:288])
	copy(v.NewPath[:], b[288:544])
	return v
}

// decodeNetPayload reads a NetPayload from b, which must be at least SizeofNetPayload bytes.
func decodeNetPayload(b []byte) NetPayload {
	var v NetPayload
	copy(v.Saddr[:], b[0:16])
	copy(v.Daddr[:], b[16:32])
	v.Bytes = int64(binary.NativeEndian.Uint64(b[32:]))
	v.Sport = binary.NativeEndian.Uint16(b[40:])
	v.Dport = binary.NativeEndian.Uint16(b[42:])
	v.Family = binary.NativeEndian.Uint16(b[44:])
	v.Protocol = binary.NativeEndian.Uint16(b[46:])
	v.SockType = binary.NativeEndian.Uint16(b[48:])
	v.Pad = binary.NativeEndian.Uint16(b[50:])
	return v
}

// decodeExecPayload reads a ExecPayload from b, which must be at least SizeofExecPayload bytes.
func decodeExecPayload(b []byte) ExecPayload {
	var v ExecPayload
	v.Argc = binary.NativeEndian.Uint32(b[0:])
	v.Pad = binary.NativeEndian.Uint32(b[4:])
	copy(v.Filename[:], b[8:264])
	for i := 0; i < 8; i++ {
		copy(v.Argv[i][:], b[264+i*64:264+(i+1)*64])
	}
	return v
}

// decodePrivPayload reads a PrivPayload from b, which must be at least SizeofPrivPayload bytes.
func decodePrivPayload(b []byte) PrivPayload {
	var v PrivPayload
	v.CapsEffective = binary.NativeEndian.Uint64(b[0:])
	v.CapsPermitted = binary.NativeEndian.Uint64(b[8:])
	v.OldUID = binary.NativeEndian.Uint32(b[16:])
	v.NewUID = binary.NativeEndian.Uint32(b[20:])
	v.Operation = binary.NativeEndian.Uint32(b[24:])
	v.Pad = binary.NativeEndian.Uint32(b[28:])
	return v
}

// decodeEvent reads a Event from b, which must be at least SizeofEvent bytes.
func decodeEvent(b []byte) Event {
	var v Event
	v.Timestamp = binary.NativeEndian.Uint64(b[0:])
	v.Type = binary.NativeEndian.Uint32(b[8:])
	v.Ret = int32(binary.NativeEndian.Uint32(b[12:]))
	v.Proc = decodeProc(b[16:72])
	copy(v.Payload[:], b[72:848])
	return v
}

// File interprets the payload union as FilePayload.
//
// Which member is valid is decided by Type, and this accessor does not check
// it. Deciding what a type value means is the decoder's job, not the ABI's.
func (v Event) File() FilePayload {
	return decodeFilePayload(v.Payload[:])
}

// Net interprets the payload union as NetPayload.
//
// Which member is valid is decided by Type, and this accessor does not check
// it. Deciding what a type value means is the decoder's job, not the ABI's.
func (v Event) Net() NetPayload {
	return decodeNetPayload(v.Payload[:])
}

// Exec interprets the payload union as ExecPayload.
//
// Which member is valid is decided by Type, and this accessor does not check
// it. Deciding what a type value means is the decoder's job, not the ABI's.
func (v Event) Exec() ExecPayload {
	return decodeExecPayload(v.Payload[:])
}

// Priv interprets the payload union as PrivPayload.
//
// Which member is valid is decided by Type, and this accessor does not check
// it. Deciding what a type value means is the decoder's job, not the ABI's.
func (v Event) Priv() PrivPayload {
	return decodePrivPayload(v.Payload[:])
}
